# ------------------------------- configuration for Event -------------------------------------#
# follow this format to specify particles to be built:
# particle_types:
#   ...
#   particle_name:
#     class: 'path.to.particle_class', if not defined it will use the default 'dtpr.particles.Particle' class
#     amount: (int, TBranch<int> or TBranch<vector>) that could define how many particles to build  
#     branches: list of branches to be used as attributes 
#       attr_name: 'branch_name' 
#       ...
#     attributes: Other attributes that can be put directly or computed with a expression or a method
#       attr_name: (value)
#         expr: 'expression' to define the attribute, it expects a expression that can use any of 
#                the class attributes directly
#         src: 'src' to define the attribute, it expects the path to a method that receives 
#                 the particle as input
#     filter: condition to filter the particles that want to be built, it expects a expression that
#             can use the particle instace (ref as 'p') and the root event entry (ref as 'ev')
#     sorter: how to sort the particles
#       by: A expresion to execute to decide the order. it expects a expression that can use the 
#           particle instance (ref as 'p') and the root event entry (ref as 'ev')
#       reverse: True/False to sort in reverse order. If not indicated default is False
#
# ================= available particles - dtntuple ================= #
# comment/uncomment/add as needed...
particle_types:
  digis:
    amount: 'digi_nDigis'
    branches:
      wh: 'digi_wheel'
      sc: 'digi_sector'
      st: 'digi_station'
      sl: 'digi_superLayer'
      w: 'digi_wire'
      l: 'digi_layer'
      time: 'digi_time'
    attributes:
      BX:
        expr: 'time // 25 if time is not None else None'
    sorter:
      by: 'p.BX'
  segments:
    amount: 'seg_nSegments'
    branches:
      wh: 'seg_wheel'
      sc: 'seg_sector'
      st: 'seg_station'
      phi: 'seg_posGlb_phi'
      eta: 'seg_posGlb_eta'
      nHits_phi: 'seg_phi_nHits'
      nHits_z: 'seg_z_nHits'
      t0_phi: 'seg_phi_t0'
      pos_locx_sl1: 'seg_posLoc_x_SL1'
      pos_locx_sl3: 'seg_posLoc_x_SL3'
    attributes:
      matched_genmuons: []
      matched_tps: []
  tps:  
    amount: 'ph2TpgPhiEmuAm_nTrigs'
    branches:
      wh: 'ph2TpgPhiEmuAm_wheel'
      sc: 'ph2TpgPhiEmuAm_sector'
      st: 'ph2TpgPhiEmuAm_station'
      phi: 'ph2TpgPhiEmuAm_phi'
      phiB: 'ph2TpgPhiEmuAm_phiB'
      BX: 'ph2TpgPhiEmuAm_BX'
      quality: 'ph2TpgPhiEmuAm_quality'
      rpcFlag: 'ph2TpgPhiEmuAm_rpcFlag'
    attributes:
      matched_segments: []
      matched_genmuons: []
      BX:
        expr: 'BX - 20' # Correct to center BX at 0
      phires_conv:
        expr: '65536.0 / 0.5'
    filter: 'p.quality >= 0'
  genmuons:
    amount: 'gen_nGenParts'
    branches:
      pt: 'gen_pt'
      eta: 'gen_eta'
      phi: 'gen_phi'
      charge: 'gen_charge'
    attributes:
      matched_segments: []
      matched_tps: []
      showered: False
    filter: 'abs(ev.gen_pdgId[p.index]) == 13'
    sorter:
      by: 'p.pt'
      reverse: True
  emushowers:
    amount: 'ph2Shower_station'
    branches:
      wh: 'ph2Shower_wheel'
      sc : 'ph2Shower_sector'
      st: 'ph2Shower_station'
      sl: 'ph2Shower_superlayer'
      nDigis: 'ph2Shower_ndigis'
      BX: 'ph2Shower_BX'
      min_wire: 'ph2Shower_min_wire'
      max_wire: 'ph2Shower_max_wire'
      avg_pos: 'ph2Shower_avg_pos'
      avg_time: 'ph2Shower_avg_time'
      wires_profile: 'ph2Shower_wires_profile'
  simhits:
    amount: 'simHit_nSimHits'
    branches:
      wh: 'simHit_wheel'
      sc: 'simHit_sector'
      st: 'simHit_station'
      sl: 'simHit_superLayer'
      l: 'simHit_layer'
      w: 'simHit_wire'
      process_type: 'simHit_processType'
      particle_type: 'simHit_particleType'
# ================= available particles - g4ntuple ================= #
  # digis:
  #   class: 'dtpr.particles.G4Digi'
  #   amount: 'nSLHit_NHits'
  #   attribute_branches:
  #     sl : 'SLHit_SL'
  #     w : 'SLHit_Cell'
  #     l : 'SLHit_Layer'
  #     time : 'SLHit_Time'
  #     particle_type : 'SLHit_PDG'
  #   attributes:
  #       time:
  #         src: 'dtpr.utils.functions.correct_g4digi_time' # this simply apply a correction to the time
  #       BX:
  #         expr: 'time // 25 if time is not None else None'
  #   sorter:
  #     by: 'p.BX'
  # simhits:
  #   class: 'dtpr.particles.G4Digi'
  #   amount: 'nSLHit_NHits'
  #   attribute_branches:
  #     sl : 'SLHit_SL'
  #     w : 'SLHit_Cell'
  #     l : 'SLHit_Layer'
  #     time : 'SLHit_Time'
  #     particle_type : 'SLHit_PDG'
  #   attributes:
  #       time:
  #         src: 'dtpr.utils.functions.correct_g4digi_time'
  #       BX:
  #         expr: 'time // 25 if time is not None else None'
  #   sorter:
  #     by: 'p.BX'

# -------------------------------- configuration for NTuple --------------------------------------#
ntuple_tree_name: '/dtNtupleProducer/DTTREE'

# =============== available preprocessors - dtntuple ================= #
# define the preprocessors to be used in the ntuple, follow the format:
# preprocessor_name: Any name, not relevant to the codes
#   src: 'path.to.preprocessor'
#   kwargs: # optional arguments to be passed to the preprocessor
#     arg1: value1
#     ...
# ...
ntuple_preprocessors:
  # # define the event preprocessors to be used in the ntuple
  genmuon_matcher:
    src: "dtpr.utils.genmuon_functions.analyze_genmuon_matches"
  genmuon_showerer:
    src: "dtpr.utils.genmuon_functions.analyze_genmuon_showers"
    kwargs:
      method: 2
  real_shower_builder:
    src: "dtpr.utils.shower_functions.build_real_showers"
    kwargs:
      threshold: 8
      debug: False
  # fw_shower_builder:
  #   src: "dtpr.utils.shower_functions.build_fwshowers"
  #   kwargs:
  #     threshold: 6
  fw_shower_analyzer:
    src: "dtpr.utils.shower_functions.analyze_fwshowers"
# ================= available selectors - dtntuple ================= #
# define the selectors to be used in the ntuple, follow the format:
# selector_name: Any name, not relevant to the codes
#   src: 'path.to.selector' 
#   kwargs: # optional arguments to be passed to the selector
#     arg1: value1
#     ...
# ...
ntuple_selectors:
# comment/uncomment/add as needed...
  baseline:
    src: "dtpr.utils.filters.base_filters.baseline"
  # removeShower:
  #   src: "dtpr.utils.filters.base_filters.removeShower"
  # baseline_plus_hitsc:
  #   src: "dtpr.utils.filters.base_filters.baseline_plus_hitsc"
  # - ...
# -------------------------------- configuration for histograms -----------------------------------#
histo_sources:
  # define the source modules of the histograms
  # - dtpr.utils.histograms.baseHistos
  - dtpr.utils.histograms.am_histos
  # - dtpr.utils.histograms.digi_histos
  # - dtpr.utils.histograms.shower_histos

histo_names:
  # Histogram to fill - Uncomment or add histograms as needed. 
  # They should exist in any of the source modules
  # # ============ efficiencies ============ #
  - seg_eff_MB1
  - seg_eff_MB2
  - seg_eff_MB3
  - seg_eff_MB4
  # - fwshower_eff_MB1
  # - fwshower_eff_MB2
  # - fwshower_eff_MB3
  # - fwshower_eff_MB4
  # # ------ conf maps------
  # - shower_tpfptnfn_MB1
  # - shower_tpfptnfn_MB2
  # - shower_tpfptnfn_MB3
  # - shower_tpfptnfn_MB4
  # - shower_tpfptnfn_g4
  # # ============== rates =============== #
  # - AM_rate_allBX_MB1
  # - AM_rate_allBX_MB2
  # - AM_rate_allBX_MB3
  # - AM_rate_allBX_MB4
  # - AM_rate_goodBX_MB1
  # - AM_rate_goodBX_MB2
  # - AM_rate_goodBX_MB3
  # - AM_rate_goodBX_MB4
  # - fwshower_rate_goodBX_MB1
  # - fwshower_rate_goodBX_MB2
  # - fwshower_rate_goodBX_MB3
  # - fwshower_rate_goodBX_MB4
  # - fwshower_rate_allBX_MB1
  # - fwshower_rate_allBX_MB2
  # - fwshower_rate_allBX_MB3
  # - fwshower_rate_allBX_MB4
  # # ============ leading_mu ============ #
  # - LeadingMuon_pt
  # - LeadingMuon_eta
  # - LeadingMuon_maxDPhi
  # - LeadingMuon_maxDEta
  # # =========== subleading_mu ========== #
  # - SubLeadingMuon_pt
  # - SubLeadingMuon_eta
  # - SubLeadingMuon_maxDPhi
  # - SubLeadingMuon_maxDEta
  # # ============= other_vars =========== #
  # - shower_eff_muon_pt
  # - shower_eff_muon_eta
  # - muon_DR
  # - nGenMuons
  # - dphimax_seg_showering_muon
  # - dphimax_seg_non_showering_muon
  # - dphimax_tp_showering_muon
  # - dphimax_tp_non_showering_muon
  # - dphi_seg_showering_muon
  # - dphi_seg_non_showering_muon
  # - dphi_tp_showering_muon
  # - dphi_tp_non_showering_muon
  # # =========== digis =========== #
  # - digi_w_gmts_MB1
  # - digi_w_gmts_MB2
  # - digi_w_gmts_MB3
  # - digi_w_gmts_MB4
  # - digi_w_gmtns_MB1
  # - digi_w_gmtns_MB2
  # - digi_w_gmtns_MB3
  # - digi_w_gmtns_MB4
  # - digi_wd_gmts_MB1
  # - digi_wd_gmts_MB2
  # - digi_wd_gmts_MB3
  # - digi_wd_gmts_MB4
  # - digi_wd_gmtns_MB1
  # - digi_wd_gmtns_MB2
  # - digi_wd_gmtns_MB3
  # - digi_wd_gmtns_MB4
  # - digi_wl_gmts_MB1
  # - digi_wl_gmts_MB2
  # - digi_wl_gmts_MB3
  # - digi_wl_gmts_MB4
  # - digi_wl3d_gmts_MB1
  # - digi_wl3d_gmts_MB2
  # - digi_wl3d_gmts_MB3
  # - digi_wl3d_gmts_MB4
  # - digi_wl_gmtns_MB1
  # - digi_wl_gmtns_MB2
  # - digi_wl_gmtns_MB3
  # - digi_wl_gmtns_MB4
  # - digi_wl3d_gmtns_MB1
  # - digi_wl3d_gmtns_MB2
  # - digi_wl3d_gmtns_MB3
  # - digi_wl3d_gmtns_MB4

# ----------------------------- configuration for event inspector ---------------------------------#
# inspector-functions:
  # define the functions to be used in the event inspector in the format:
  # func1:
  #   src: "dtpr.utils.inspector_functions.digi_inspector"
  #   kwargs:
  #     arg1: value1
  #     ...
  #   ...

# ------------------------------- configuration for dt plots  -------------------------------------#
dt_plots_configs:
  mplhep-style: 'CMS'         # Style to use for the plots

  figure-configs: 
    figure.dpi: 100             # Dots per inch (resolution)
    axes.titlesize: 'small'     # Axes title size
    axes.labelsize: 'x-small'    # Axes label size
    xtick.labelsize: 'x-small'    # X-axis tick label size
    ytick.labelsize: 'x-small'    # Y-axis tick label size
    legend.fontsize: 'small'   # Legend font size

  dt-cell-info:
    particle_type: 'digis'      # Particle type to use
    cmap_var: 'time'            # Variable to use for the colormap

  cmap-configs:
    cmap: 'viridis'             # Colormap to use
    cmap_under: 'none'          # Color for values under vmin
    norm:
      class: 'matplotlib.colors.Normalize'  # Normalization class
      vmin: 299                             # Minimum value for normalization
      vmax: 1000                            # Maximum value for normalization

  # DT bounds and cells are matplotlib.patches.Rectangle objects
  bounds-kwargs:
    facecolor: ["lightgray", "lightyellow", "lightpink", "lightblue"]   # Color of the rectangle [MB, SL1, SL3, SL2]
    edgecolor: "k"                                                      # Color of the edge
    alpha: 0.3                                                          # Transparency of the rectangle
    linewidth: 0.5                                                      # Width of the edge

  cells-kwargs:
    edgecolor: "k"              # Color of the edge
    linewidth: 0.025              # Width of the edge
